### PR TITLE
Update forms.md

### PR DESCRIPTION
**Pull request by marclar**
This section was out of date for me; here are some updated instructions (at least for MacOS Sonoma 14).

### CODE REVIEW

**Comment by AucaCoyan** [comment]
Thank you! One tiny question: how come we can call an image from the asset url, but it's not stored in the repo 🤔. Is it a temporary storage?

**Comment by marclar** [comment]
I wasn't sure how to add an image through the web UI (I didn't have a fork at the time), so I dragged it as a comment and it uploaded to that URL.

But you're 100% right to call that out; it should be moved to the repo -- I'm just away from the desk. lmk if you can do it, otherwise I can in an hour or 2

**Comment by marclar** [comment]
Actually... now that I look, I remember the reason I felt comfortable leaving it: it's hosted under your organization, so I don't think it'll get deleted, unless explicitly. That said, it should still probably be moved.

**Comment by AucaCoyan** [comment]
Sure! Just add the picture to the repo. `static/img/docs` seems a start, but you can choose other place too

**Comment by AucaCoyan** [comment]
Superseded by #52

**Pull request closed without merging**
