### PR TITLE
Update _x11-after-install.mdx

### PR DESCRIPTION
**Pull request by fpetrakov**
This way it's much easier to copy commands with "copy button" than before

### CODE REVIEW

**Comment by smeech** [comment]
Thank you.

Do you think it's necessary to separate the commands, to run the process in two stages?

**Comment by fpetrakov** [comment]
@smeech the problem is that pressing "copy button" copies not only commands, but the comments too, so it's kinda useless right now

**Comment by smeech** [comment]
Apologies for being dense, but what problem does that cause you?

**Comment by smeech** [comment]
Thanks! Had me worried for a while!

Best wishes,

**Pull request closed without merging**
