### PR TITLE
Update basics.md

### PR DESCRIPTION
**Pull request by jpa38**
Juste change the windows's path with an windows 's variable able to all users. You can copy/paste the path and it's work for all !

### CODE REVIEW

**Comment by smeech** [comment]
Sorry for the late reply - I'm trying to mop up old Issues and looking out for documentation updates.

This suggestion applies to an old version of the docs (the current location for this content is get-started.md).

Whilst it's a good suggestion, it would introduce an inconsistency unless we dd the same for Linux & macOS?

**Comment by AucaCoyan** [comment]
@smeech I'm merging this, can you take note to update the path for linux and mac too? I don't know if you have done it already 😄

**Comment by AucaCoyan** [comment]
Thank you @jpa38 !

**Comment by smeech** [comment]
> @smeech I'm merging this, can you take note to update the path for linux and mac too? I don't know if you have done it already 😄

Done Linux. Just asking on Discord about macOS. Once I have that I'll submit a PR for all my recent changes.

**Pull request merged**
