### PR TITLE
chores: federico-terzi/espanso to espanso/espanso

### PR DESCRIPTION
**Pull request by NoPlagiarism**
Not changed:
- [This line](https://github.com/NoPlagiarism/espanso-website/blob/d1ed428b0413abdd6baee84fc132d7c5ee4d529a/docusaurus.config.js#L15). Didn't know if I should change the `organizationName` in `DocusaurusConfig`
- [This line](https://github.com/NoPlagiarism/espanso-website/blob/d1ed428b0413abdd6baee84fc132d7c5ee4d529a/docs/install/mac.mdx#L48) that tell to untap old package on Mac (obvi)
- [This gist link](https://gist.github.com/federico-terzi/b6465dfcca47e86e9ef0eb597ff6f2e9). Is there a way or need to move gist to the organisation?
- \+ All version-0.7.3 docs

### CODE REVIEW

**Comment by smeech** [comment]
Sorry for the late reply - I'm trying to mop up old Issues and suggestions.

It would be nice to do this, although the current links redirect correctly. I guess we'd have to apply the changes to the current version of the docs, however?

**Comment by AucaCoyan** [comment]
Yes! I also replaced the links in my current pr #34 , but the items in the descriptions aren't covered.
In any case, I can deal with a merge conflict no problem, as this is a simple string transformation.

Did you had the chance to check the points in the description smeech?

**Comment by smeech** [comment]
Yes - I just noticed the updated links - thanks!
> Not changed:
> 
> * [This line](https://github.com/NoPlagiarism/espanso-website/blob/d1ed428b0413abdd6baee84fc132d7c5ee4d529a/docusaurus.config.js#L15). Didn't know if I should change the `organizationName` in `DocusaurusConfig`

Yes, as long as @federico-terzi doesn't mind - the project is much more collaborative now.
> * [This line](https://github.com/NoPlagiarism/espanso-website/blob/d1ed428b0413abdd6baee84fc132d7c5ee4d529a/docs/install/mac.mdx#L48) that tell to untap old package on Mac (obvi)

Yes
> * [This gist link](https://gist.github.com/federico-terzi/b6465dfcca47e86e9ef0eb597ff6f2e9). Is there a way or need to move gist to the organisation?
> * + All version-0.7.3 docs

I can't see where that appears?

**Comment by AucaCoyan** [comment]
The gist url is `https://gist.github.com/federico-terzi/` but it can be moved to `espanso`, idk if organizations can have gists 🤔 
We could have another page in the docs anyway, we don't need specifically a gist

**Comment by smeech** [comment]
It doesn't appear to be anything directly related to Espanso, does it? I assumed it was something @federico-terzi kept for personal reference.

**Comment by smeech** [comment]
Ah - found the link here: https://espanso.org/docs/matches/extensions/#advanced-localized-dates
I think we should link to an authoritative third party, if possible.

**Comment by AucaCoyan** [comment]
OR, we could link to `chrono` library instead, which is our provider.
Locales are provided by [this](https://github.com/espanso/espanso/blob/dev/espanso-render/src/extension/date.rs#L102) function right there, and `Locale` comes from [this enum](https://docs.rs/chrono/latest/chrono/enum.Locale.html).
We can write a note in the documentation that says something like: "here are all the locales, coming from `crono`. If you are missing someone, contact us on github / discord"

and we solve this and the Locales problem 😄

**Comment by smeech** [comment]
Does that automatically update the output of the `date` var?

**Comment by NoPlagiarism** [comment]
> project is much more collaborative now.

I mean, I just don't know if it will break anything or sth like that

**Comment by AucaCoyan** [comment]
> I'm just concerned that might result in someone using a locale code that isn't hard-coded

No, don't worry, this line [here](https://github.com/espanso/espanso/blob/dfd695b8e0173d0c8c71e17714c6074cf641b7bd/espanso-render/src/extension/date.rs#L406)
```rust
    _ => None,
```
Says that if it doesn't find the string among the enum, returns nothing. You cant select an enum that is not hardcoded. `_` means "any other remaining enum case"

**Comment by NoPlagiarism** [comment]
> The available keys are defined [here](https://github.com/espanso/espanso/blob/283b85818b6cc27f1d545337b99effa847b380eb/espanso-inject/src/keys.rs#L237-L323)

This line is bothering me. It's using 3yr ago commit (espanso/espanso@283b85818b6cc27f1d545337b99effa847b380eb)

Maybe change it to newer one?

**Comment by AucaCoyan** [comment]
> This line is bothering me. It's using 3yr ago commit (https://github.com/espanso/espanso/commit/283b85818b6cc27f1d545337b99effa847b380eb)
Maybe change it to newer one?

Mmmm, I don't get what you mean, can you explain it a bit further?

Some points around the topic, but I don't know specifically what are you looking for:
- in terms of commit age, espanso codebase is old all-around. We have a crate dependency that is 7 years old, that is a lot in the rust ecosystem. I'm on my path to update, but I'm afraid that I cannot make changes until we have some tests to prove that the thing doesn't break. (_make changes easy, then make the easy change_ is something I say to myself often)
- (about the issue description) Docusaurus is updated to v3 already, I have a PR to update it, but it's stalled until I can see the error logs
- and we agree with smeech that it would be better to have the gist inside the docs, not as a github gist.

**Comment by NoPlagiarism** [comment]
> I don't get what you mean

I'm talking exactly about key list, mentioned in `paste_shortcut`

**Comment by smeech** [comment]
> > I don't get what you mean
> 
> I'm talking exactly about key list, mentioned in `paste_shortcut`

What bothers you about it? I think it links to the current version of the code, doesn't it? Not that many people will need to change the paste setting, I suppose.

**Comment by smeech** [comment]
> The gist url is `https://gist.github.com/federico-terzi/` but it can be moved to `espanso`, idk if organizations can have gists 🤔 We could have another page in the docs anyway, we don't need specifically a gist

We could just link to the original at https://gist.github.com/typpo/b2b828a35e683b9bf8db91b5404f1bd1. It's being maintained more actively than ours, so doesn't contain the errors. I think I'll include it in my next update to the docs, unless you disagree? Then we can dispense with our copy.

**Comment by smeech** [comment]
Shall I go ahead and merge this?

I can resolve the conflicts in the web editor - they're simply where I have folded the Option names in the [Options reference](https://espanso.org/docs/configuration/options/#options-reference) to improve the appearance of the table. I need to retain my edits.

**Comment by smeech** [comment]
I think that's ready to merge.

The only uncertainty I have is the implications of the changes in the docusaurus `Contributing.js` and `Navigation.js`. They _look_ fine.

**Pull request merged**
