### PR TITLE
Update organizing-matches.md

### PR DESCRIPTION
**Pull request by kristus123**
no idea why it has git diffed the unchanged line

### CODE REVIEW

**Comment by smeech** [comment]
> no idea why it has git diffed the unchanged line

Probably because you've added a newline to what was the end of the file.

**Comment by AucaCoyan** [comment]
If I understood correctly, this PR can be closed?
Or maybe we can leave a link at the end of `organizing-matches.md` to App-specific configurations.

**Comment by smeech** [comment]
I would close it. I think the existing "Tip" is sufficient.

**Comment by kristus123** [comment]
as someone who is not familiar with espanso, having that information there would be really helpful.
i spent quite some time digging through the documentation in order to find it, so i (and many others) would save time to have that tip located there

**Comment by smeech** [comment]
How about if we put another link to “app-specific configuration” in line 101?

**Comment by smeech** [comment]
Thank you.
It's certainly something to bear in mind if others seem to have the same problem.

**Pull request closed without merging**
